---
title: "homework 3"
format:
  html:
    self-contained: true
---

1. (1 point) Add your name, yale netid, and github account to [this shared document](https://yale.instructure.com/courses/81394/collaborations/5950).
1. (1 points) Get a copy of my bis620.2022 package. Increase the test coverage of the bis620.2022 package to at 
least 95\%. 
1. (1 point) Call `lintr::lint()` on the package and fix all issues.
1. (1 point) Create a repository called bis620.2022 on Github and add your updated package to it. 
1. (1 point) Add a github action to test the package anytime it is pushed to the repository. 
1. (1 point) Add a github action to calculate the test coverage (see https://github.com/r-lib/actions and  `usethis::use_github_actions("test-coverage"`)). 
1. (1 point) Add a github action to lint the package (`usethis::use_github_actions("lint")`).
1. Add a README.Rmd file with 
    1. (1 point) A short description of the package and its usage.
    1. (1 point) A badge indicating if the build was successful.
    1. (1 point) A link to the coverage page and lint results.